import { CalendarCheck, CalendarClock, Download, Eraser, Eye, ListFilter, Pencil, Plus, Save, Users, XCircle } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { ActionNotice } from '../../../components/ui/ActionNotice'
import { Avatar } from '../../../components/ui/Avatar'
import { Button } from '../../../components/ui/Button'
import { ConfirmModal } from '../../../components/ui/ConfirmModal'
import { Modal } from '../../../components/ui/Modal'
import { Pagination } from '../../../components/ui/Pagination'
import { StatusBadge } from '../../../components/ui/StatusBadge'
import { useActionNotice } from '../../../hooks/useActionNotice'
import { useResource } from '../../../hooks/useResource'
import { api } from '../../../services/api'
import { resourceService } from '../../../services/resourceService'
import { downloadCsv } from '../../../utils/exportUtils'
import { apiError, formatDateTime, userName } from '../../../utils/formatters'

const statuses = ['pending', 'confirmed', 'cancelled', 'completed', 'no_show']
const statusLabels = { pending: 'En attente', confirmed: 'Confirmé', cancelled: 'Annulé', completed: 'Terminé', no_show: 'Absent' }
const emptyForm = { patient_id: '', doctor_id: '', department_id: '', scheduled_at: '', reason: '', status: 'pending' }

export function AdminAppointmentsPage() {
  const [status, setStatus] = useState('')
  const [department, setDepartment] = useState('')
  const [date, setDate] = useState('')
  const [page, setPage] = useState(1)
  const [stats, setStats] = useState(null)
  const [form, setForm] = useState(emptyForm)
  const [editing, setEditing] = useState(null)
  const [formOpen, setFormOpen] = useState(false)
  const [viewing, setViewing] = useState(null)
  const [isSaving, setIsSaving] = useState(false)
  const [workingId, setWorkingId] = useState(null)
  const [pendingStatus, setPendingStatus] = useState(null)
  const { items: appointments, pagination, isLoading, error, refetch } = useResource('appointments', { status, department_id: department, date, page, per_page: 10 })
  const { items: departments } = useResource('departments', { per_page: 100 })
  const { items: doctors } = useResource('doctors', { per_page: 100 })
  const { items: patients } = useResource('patients', { per_page: 100 })
  const { message, notify, clear } = useActionNotice()
  useEffect(() => { api.get('/admin/dashboard').then(({ data }) => setStats(data)).catch(() => setStats(null)) }, [])
  const cancelled = useMemo(() => appointments.filter((item) => item.status === 'cancelled').length, [appointments])
  const formDoctors = useMemo(() => doctors.filter((doctor) => !form.department_id || String(doctor.department_id) === String(form.department_id)), [doctors, form.department_id])

  function openCreate() { setEditing(null); setForm(emptyForm); setFormOpen(true) }
  function openEdit(appointment) { setEditing(appointment.id); setForm({ patient_id: appointment.patient_id, doctor_id: appointment.doctor_id, department_id: appointment.department_id, scheduled_at: appointment.scheduled_at?.slice(0, 16) ?? '', reason: appointment.reason ?? '', status: appointment.status }); setFormOpen(true) }
  async function save(event) { event.preventDefault(); if (isSaving) return; setIsSaving(true); try { if (editing) await resourceService.update('appointments', editing, form); else await resourceService.create('appointments', form); setFormOpen(false); setEditing(null); setForm(emptyForm); await refetch(); notify('Rendez-vous enregistré.') } catch (requestError) { notify(apiError(requestError, "Impossible d’enregistrer le rendez-vous.")) } finally { setIsSaving(false) } }
  async function commitStatus(id, nextStatus) { if (workingId) return; setWorkingId(id); try { await resourceService.update('appointments', id, { status: nextStatus }); await refetch(); setPendingStatus(null); notify('Statut mis à jour.') } catch (requestError) { notify(apiError(requestError, 'Impossible de mettre à jour le rendez-vous.')) } finally { setWorkingId(null) } }
  function changeStatus(appointment, nextStatus) { if (nextStatus === 'cancelled') { setPendingStatus({ id: appointment.id, name: userName(appointment.patient) }); return } commitStatus(appointment.id, nextStatus) }
  function resetFilters() { setStatus(''); setDepartment(''); setDate(''); setPage(1) }
  function exportCsv() { downloadCsv('rendez-vous-smart-hospital.csv', [['Patient', 'Médecin', 'Date', 'Département', 'Statut'], ...appointments.map((item) => [userName(item.patient), userName(item.doctor), formatDateTime(item.scheduled_at), item.department?.name, statusLabels[item.status] || item.status])]); notify('Export CSV téléchargé.') }

  return <div className="page-stack">
    <ActionNotice message={message} onClose={clear} />
    <section className="grid gap-5 xl:grid-cols-[2fr_1fr]"><article className="rounded-2xl bg-gradient-to-r from-blue-700 to-blue-500 p-7 text-white shadow-lg shadow-blue-900/15 sm:p-8"><h2 className="text-3xl font-bold sm:text-4xl">Gestion des Rendez-vous</h2><p className="mt-3 max-w-2xl text-lg text-blue-50">Planifiez, filtrez et suivez les visites patient dans tous les départements.</p><div className="mt-8 flex flex-wrap gap-3"><Button variant="secondary" onClick={() => document.getElementById('appointments-table')?.scrollIntoView()}><CalendarCheck size={18} />Voir le planning</Button><Button onClick={openCreate}><Plus size={18} />Créer un rendez-vous</Button><Button onClick={exportCsv} className="bg-blue-900/50 hover:bg-blue-900/70"><Download size={18} />Exporter</Button></div></article><div className="grid grid-cols-2 gap-4"><article className="panel p-5"><Users className="text-blue-600" /><p className="muted mt-5 text-sm">Total patients</p><strong className="text-2xl">{stats?.total_patients ?? '—'}</strong></article><article className="panel p-5"><CalendarCheck className="text-emerald-600" /><p className="muted mt-5 text-sm">Aujourd’hui</p><strong className="text-2xl">{stats?.appointments_today ?? '—'}</strong></article><article className="panel p-5"><CalendarClock className="text-amber-600" /><p className="muted mt-5 text-sm">En attente</p><strong className="text-2xl">{stats?.pending_appointments ?? '—'}</strong></article><article className="panel p-5"><XCircle className="text-red-600" /><p className="muted mt-5 text-sm">Annulés affichés</p><strong className="text-2xl">{cancelled}</strong></article></div></section>
    <section className="panel flex flex-col gap-4 p-5 lg:flex-row lg:items-end"><label className="field-label lg:w-56">Date<input type="date" value={date} onChange={(event) => { setDate(event.target.value); setPage(1) }} className="field" /></label><label className="field-label lg:w-64">Département<select value={department} onChange={(event) => { setDepartment(event.target.value); setPage(1) }} className="field"><option value="">Tous les départements</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field-label lg:w-56">Statut<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }} className="field"><option value="">Tous les statuts</option>{statuses.map((item) => <option key={item} value={item}>{statusLabels[item]}</option>)}</select></label><Button variant="ghost" onClick={resetFilters} className="lg:ml-auto"><Eraser size={18} />Effacer les filtres</Button></section>
    <section id="appointments-table" className="panel overflow-hidden"><div className="flex items-center justify-between border-b px-6 py-5" style={{ borderColor: 'var(--border)' }}><h3 className="text-xl font-bold">Rendez-vous planifiés</h3><ListFilter className="muted" size={20} /></div>{error ? <p role="alert" className="m-5 rounded-xl bg-red-50 p-3 text-red-700">{apiError(error, 'Impossible de charger les rendez-vous.')}</p> : null}<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead className="table-head text-xs uppercase tracking-widest"><tr>{['Patient', 'Médecin', 'Date & heure', 'Département', 'Motif', 'Statut', 'Actions'].map((head) => <th key={head} className="px-6 py-4">{head}</th>)}</tr></thead><tbody>{isLoading ? <tr><td colSpan="7" className="muted px-6 py-8">Chargement...</td></tr> : appointments.length ? appointments.map((row) => <tr key={row.id} className="table-row border-t"><td className="px-6 py-4"><div className="flex items-center gap-3"><Avatar name={userName(row.patient)} /><strong>{userName(row.patient)}</strong></div></td><td className="px-6 py-4">{userName(row.doctor)}</td><td className="px-6 py-4">{formatDateTime(row.scheduled_at)}</td><td className="px-6 py-4">{row.department?.name}</td><td className="muted max-w-52 truncate px-6 py-4">{row.reason || '—'}</td><td className="px-6 py-4"><label className="inline-flex items-center gap-2"><StatusBadge status={row.status} /><select value={row.status} disabled={workingId === row.id} onChange={(event) => changeStatus(row, event.target.value)} className="field min-h-9 w-10 px-1 text-transparent" aria-label={`Modifier le statut du rendez-vous de ${userName(row.patient)}`}>{statuses.map((item) => <option key={item} value={item}>{statusLabels[item]}</option>)}</select></label></td><td className="px-6 py-4"><div className="flex gap-1"><button type="button" onClick={() => setViewing(row)} className="icon-button" aria-label={`Voir le rendez-vous de ${userName(row.patient)}`} title="Voir"><Eye size={18} /></button><button type="button" onClick={() => openEdit(row)} className="icon-button" aria-label={`Modifier le rendez-vous de ${userName(row.patient)}`} title="Modifier"><Pencil size={18} /></button></div></td></tr>) : <tr><td colSpan="7" className="muted px-6 py-10 text-center">Aucun rendez-vous.</td></tr>}</tbody></table></div><Pagination pagination={pagination} onPageChange={setPage} /></section>
    <section className="grid gap-5 md:grid-cols-3">{[{ icon: CalendarCheck, title: 'Suivi centralisé', text: 'Tous les rendez-vous utilisent les données API existantes.' }, { icon: CalendarClock, title: 'Statuts en temps réel', text: 'Confirmez, terminez ou signalez une absence.' }, { icon: Download, title: 'Export rapide', text: 'Téléchargez la sélection affichée au format CSV.' }].map((item) => <article key={item.title} className="panel flex gap-4 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-950/50 dark:text-blue-300"><item.icon size={21} /></span><div><h3 className="font-bold">{item.title}</h3><p className="muted mt-1 text-sm">{item.text}</p></div></article>)}</section>
    <Modal open={formOpen} onClose={isSaving ? () => {} : () => setFormOpen(false)} title={editing ? 'Modifier le rendez-vous' : 'Créer un rendez-vous'} size="3xl"><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><label className="field-label">Patient<select required value={form.patient_id} onChange={(event) => setForm({ ...form, patient_id: event.target.value })} className="field"><option value="">Choisir un patient</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{userName(patient)}</option>)}</select></label><label className="field-label">Département<select required value={form.department_id} onChange={(event) => setForm({ ...form, department_id: event.target.value, doctor_id: '' })} className="field"><option value="">Choisir un département</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field-label">Médecin<select required value={form.doctor_id} onChange={(event) => setForm({ ...form, doctor_id: event.target.value })} className="field"><option value="">Choisir un médecin</option>{formDoctors.map((doctor) => <option key={doctor.id} value={doctor.id}>{userName(doctor)}</option>)}</select></label><label className="field-label">Date et heure<input required type="datetime-local" min={editing ? undefined : new Date().toISOString().slice(0, 16)} value={form.scheduled_at} onChange={(event) => setForm({ ...form, scheduled_at: event.target.value })} className="field" /></label><label className="field-label">Statut<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="field">{statuses.map((item) => <option key={item} value={item}>{statusLabels[item]}</option>)}</select></label><label className="field-label sm:col-span-2">Motif<textarea value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} className="field min-h-24 resize-y" /></label><div className="flex justify-end gap-3 sm:col-span-2"><Button variant="secondary" onClick={() => setFormOpen(false)} disabled={isSaving}>Annuler</Button><Button type="submit" disabled={isSaving}><Save size={18} />{isSaving ? 'Enregistrement...' : 'Enregistrer'}</Button></div></form></Modal>
    <Modal open={Boolean(viewing)} onClose={() => setViewing(null)} title="Détails du rendez-vous"><dl className="grid gap-4 sm:grid-cols-2">{viewing ? [['Patient', userName(viewing.patient)], ['Médecin', userName(viewing.doctor)], ['Département', viewing.department?.name], ['Date', formatDateTime(viewing.scheduled_at)], ['Statut', statusLabels[viewing.status]], ['Motif', viewing.reason]].map(([label, value]) => <div key={label} className="panel-muted rounded-xl border p-4"><dt className="eyebrow">{label}</dt><dd className="mt-2 font-semibold">{value || '—'}</dd></div>) : null}</dl></Modal>
    <ConfirmModal open={Boolean(pendingStatus)} onClose={() => setPendingStatus(null)} onConfirm={() => commitStatus(pendingStatus.id, 'cancelled')} isLoading={Boolean(workingId)} title="Annuler le rendez-vous" description={`Confirmez l’annulation du rendez-vous de ${pendingStatus?.name || 'ce patient'}.`} confirmLabel="Annuler le rendez-vous" />
  </div>
}
