import { useId, useMemo } from 'react'

export function LineChart({ data = [], series = [{ key: 'appointments', label: 'Rendez-vous', color: '#1459d9' }], height = 250 }) {
  const gradientId = useId().replaceAll(':', '')
  const maximum = Math.max(...data.flatMap((item) => series.map((entry) => Number(item[entry.key]) || 0)), 1)
  const pointsFor = (key) => data.map((item, index) => ({ x: data.length <= 1 ? 50 : 5 + (index * 90) / (data.length - 1), y: 84 - ((Number(item[key]) || 0) / maximum) * 66 }))
  return <div><div className="mb-4 flex flex-wrap justify-end gap-4">{series.map((item) => <span key={item.key} className="muted flex items-center gap-2 text-xs font-semibold"><i className="h-2.5 w-2.5 rounded-full" style={{ background: item.color }} />{item.label}</span>)}</div><svg viewBox="0 0 100 100" className="w-full" style={{ height }} role="img" aria-label="Graphique d'évolution">{[18, 40, 62, 84].map((y) => <line key={y} x1="5" x2="95" y1={y} y2={y} stroke="var(--border)" strokeWidth="0.6" />)}<defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={series[0]?.color || '#1459d9'} stopOpacity=".18" /><stop offset="1" stopColor={series[0]?.color || '#1459d9'} stopOpacity="0" /></linearGradient></defs>{series.map((entry, seriesIndex) => { const points = pointsFor(entry.key); const path = points.map((point, index) => `${index ? 'L' : 'M'} ${point.x} ${point.y}`).join(' '); const area = points.length ? `${path} L ${points.at(-1).x} 86 L ${points[0].x} 86 Z` : ''; return <g key={entry.key}>{seriesIndex === 0 && area ? <path d={area} fill={`url(#${gradientId})`} /> : null}{path ? <path d={path} fill="none" stroke={entry.color} strokeWidth="1.8" vectorEffect="non-scaling-stroke" /> : null}{points.map((point, index) => <circle key={index} cx={point.x} cy={point.y} r="1.35" fill={entry.color} />)}</g> })}</svg><div className="grid text-center text-xs font-medium text-[var(--muted)]" style={{ gridTemplateColumns: `repeat(${Math.max(data.length, 1)}, minmax(0, 1fr))` }}>{data.map((item, index) => <span key={item.label || index}>{item.label}</span>)}</div></div>
}

export function BarChart({ data = [], dataKey = 'value', color = '#1459d9' }) {
  const max = Math.max(...data.map((item) => Number(item[dataKey]) || 0), 1)
  return <div className="flex h-64 items-end gap-3 border-b px-2 pb-0" style={{ borderColor: 'var(--border)' }}>{data.map((item, index) => <div key={item.label || index} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="muted text-xs font-semibold">{item[dataKey]}</span><div className="w-full max-w-16 rounded-t-lg" style={{ height: `${Math.max(((Number(item[dataKey]) || 0) / max) * 180, 4)}px`, background: color, opacity: 0.78 }} /><span className="muted truncate text-xs">{item.label}</span></div>)}</div>
}

export function DonutChart({ data = [], centerLabel }) {
  const total = data.reduce((sum, item) => sum + Number(item.value || 0), 0)
  const gradient = useMemo(() => data.map((item, index) => { const start = total ? (data.slice(0, index).reduce((sum, entry) => sum + Number(entry.value || 0), 0) / total) * 100 : 0; const end = total ? start + (item.value / total) * 100 : 0; return `${item.color} ${start}% ${end}%` }).join(', ') || '#dbe3ef 0 100%', [data, total])
  return <div className="grid gap-6 sm:grid-cols-[180px_1fr] sm:items-center"><div className="relative mx-auto h-44 w-44 rounded-full" style={{ background: `conic-gradient(${gradient})` }}><div className="absolute inset-6 grid place-items-center rounded-full bg-[var(--surface)] text-center"><div><strong className="block text-2xl">{centerLabel ?? total}</strong><span className="muted text-xs">Total</span></div></div></div><div className="space-y-3">{data.map((item) => <div key={item.label} className="flex items-center gap-3 text-sm"><i className="h-2.5 w-2.5 rounded-full" style={{ background: item.color }} /><span className="min-w-0 flex-1 truncate">{item.label}</span><strong>{total ? Math.round((item.value / total) * 100) : 0}%</strong></div>)}</div></div>
}
